[plantuml,replication-sequence, svg]
....
participant SlaveReplWorkTrashDir
participant SlaveReplWorkDir
participant SlaveIndexDir
participant Slave
participant Master
participant MasterIndexDir

==== starting the replication process ====
Slave->Master : replication session request
Master<->MasterIndexDir : takes a snapshot
Master->Slave : returns the file list and the index UUID

==== choosing a replication strategy ====
Slave->Slave : Chooses the replication strategy
note left
  If the master index UUID did not change
  the incremental strategy is choosen,
  if not the full copy strategy is choosen.
end note

==== Alternative: Incremental replication process ====
Slave<->SlaveIndexDir : compares local files and the given file list
Slave->MasterIndexDir : requests the diff files
MasterIndexDir->Slave : returns the requested files
Slave->SlaveReplWorkDir : stores the new files
SlaveReplWorkDir->SlaveIndexDir : moves the new files
Slave->SlaveIndexDir : reloads the IndexSearcher/IndexReader
Slave->SlaveIndexDir : deletes the old files

==== Alternative: Full replication process ====
Slave->MasterIndexDir : requests every index files
MasterIndexDir->Slave : returns the requested files
Slave->SlaveReplWorkDir : stores the new files
SlaveIndexDir->SlaveReplWorkTrashDir : moves the old files
SlaveReplWorkDir->SlaveIndexDir : moves the new files
Slave->SlaveIndexDir : reloads the IndexSearcher/IndexReader
Slave->SlaveReplWorkTrashDir : deletes the old files

==== ending the replication process ====
Slave->Master : release replication session
Master->MasterIndexDir : release snapshot
....
