name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        java: [ '11', '17']
    name: Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
          check-latest: true
      - name: Build with Maven
        run: mvn -B test
